### ISSUE TITLE
Not working with 6.6.25

### ISSUE THREAD

**Issue by OJHeen** [ios-xr/gisobuild#3]
Hi, we have tried to use it with XR 6.6.25 but it wont load in the configuration then. 

We get it to work with XR 6.5.3 perfectly

Is there some features that are unsupported in 6.6.25 that is making it break?

**Comment by cmohapat** [comment]
Hi Jheen,

Could you please share what exactly you have tried and it didn't work ?

Kind Regards,
-Chandan

**Comment by N0bleA** [comment]
Hey, we have some problem with migrating our router from 32 bit to 64 bit. We try migrate from 6.1.4 to 6.6.3. The error we got is given below.

Traceback (most recent call last):
File "/usr/local/csm/csmserver/work_units/install_work_unit/base.py", line 125, in start
handler.execute(ctx)
File "/usr/local/csm/csmserver/handlers/base.py", line 97, in execute
raise e
TypeError: 'list' object cannot be interpreted as an index

Have you ever experince such problem if so what is the possible solution ?

**Comment by cmohapat** [comment]
Hi,

This issue no longer exist. So closing the case.

Kind Regards,
-Chandan
