### ISSUE TITLE
Struggling with a GISO for NCS540l - Unable to group the following XR packages into blocks

### ISSUE THREAD

**Issue by tactic123** [ios-xr/gisobuild#52]
Hi there,
trying to get a new GISO for 7.7.21 setup but struggling when adding the related optional RPMs:
Gisobuild script failed, see /home/pi/7.7.21/output_gisobuild/logs/gisobuild.log for more info: Unable to group the following XR packages into blocks:
  xr-bgp-n540-28z4c-7.7.21v1.0.0-1.x86_64
  xr-ipsla-n540-28z4c-7.7.21v1.0.0-1.x86_64
  xr-is-is-n540-28z4c-7.7.21v1.0.0-1.x86_64
  xr-telnet-n540-28z4c-7.7.21v1.0.0-1.x86_64
  .....

seems this applies only to rpms with n540-28z4c in the name. All others are passing through
checking the logs won't give me a hint. Any ideas?

**Comment by NeilKetley** [comment]
Could you please provide more details on which RPMs you have in the location referenced by the `--repo` argument and what the full command you invoked the gisobuild script with was?  For example, for BGP, could you please list out all the RPMs you have?

**Comment by tactic123** [comment]
thanks for the reply. Here ist the things I did.
So it seems some of the rpms are fine, and some of the ones with n540-28.. in their name not, e.g. the bgp one.
I assume the FileNotFoundError: [Errno 2] No such file or directory: 'isosize' is due to the RPM error

**content of the folder referenced:**
ncs540l-x64-7.7.21.iso
output_gisobuild
xr-bgp-n540-28z4c-7.7.21v1.0.0-1.x86_64.rpm
xr-cfgmgr-7.7.21v1.0.3-1.x86_64.rpm
xr-cfgmgr-n540-28z4c-7.7.21v1.0.3-1.x86_64.rpm
xr-core-7.7.21v1.0.1-1.x86_64.rpm
xr-core-n540-28z4c-7.7.21v1.0.1-1.x86_64.rpm
xr-diskboot-7.7.21v1.0.2-1.x86_64.rpm
xr-diskboot-n540-28z4c-7.7.21v1.0.2-1.x86_64.rpm
xr-install-7.7.21v1.0.2-1.x86_64.rpm
xr-install-n540-28z4c-7.7.21v1.0.2-1.x86_64.rpm
xr-ipsla-n540-28z4c-7.7.21v1.0.0-1.x86_64.rpm
xr-is-is-n540-28z4c-7.7.21v1.0.0-1.x86_64.rpm
xr-lictrl-n540-28z4c-7.7.21v1.0.0-1.x86_64.rpm
xr-lldp-n540-28z4c-7.7.21v1.0.0-1.x86_64.rpm
xr-mcast-n540-28z4c-7.7.21v1.0.0-1.x86_64.rpm
xr-mpls-oam-n540-28z4c-7.7.21v1.0.0-1.x86_64.rpm
xr-ncs540l-core-7.7.21v1.0.18-1.x86_64.rpm
xr-ncs540l-core-n540-28z4c-7.7.21v1.0.18-1.x86_64.rpm
xr-ncs540l-mcast-n540-28z4c-7.7.21v1.0.0-1.x86_64.rpm
xr-ncs540l-netflow-n540-28z4c-7.7.21v1.0.0-1.x86_64.rpm
xr-netflow-n540-28z4c-7.7.21v1.0.0-1.x86_64.rpm
xr-perfmgmt-n540-28z4c-7.7.21v1.0.0-1.x86_64.rpm
xr-spi-core-7.7.21v1.0.2-1.x86_64.rpm
xr-spi-core-n540-28z4c-7.7.21v1.0.2-1.x86_64.rpm
xr-telnet-n540-28z4c-7.7.21v1.0.0-1.x86_64.rpm
xr-track-n540-28z4c-7.7.21v1.0.0-1.x86_64.rpm

**command:**
`user@server:~$` ./gisobuild/src/gisobuild.py --iso /home/pi/7.7.21/ncs540l-x64-7.7.21.iso --repo /home/pi/7.7.21/ --clean`


**output:**
`user@server:~$` ./gisobuild/src/gisobuild.py --iso /home/pi/7.7.21/ncs540l-x64-7.7.21.iso --repo /home/pi/7.7.21/ --clean
Gisobuild script failed, see /home/pi/output_gisobuild/logs/gisobuild.log for more info: Failed to run image.py with command /usr/bin/python3 /tmp/giso_build_30rh2v76/iso/tools/image.py query-content -L /home/pi/output_gisobuild/logs/iso_image.log -i /home/pi/7.7.21/ncs540l-x64-7.7.21.iso: Command '['/usr/bin/python3', '/tmp/giso_build_30rh2v76/iso/tools/image.py', 'query-content', '-L', '/home/pi/output_gisobuild/logs/iso_image.log', '-i', '/home/pi/7.7.21/ncs540l-x64-7.7.21.iso']' returned non-zero exit status 1.

Full output:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/giso_build_30rh2v76/iso/tools/image.py/__main__.py", line 3, in <module>
  File "/tmp/giso_build_30rh2v76/iso/tools/image.py/image.py", line 4581, in main
  File "/tmp/giso_build_30rh2v76/iso/tools/image.py/image.py", line 1599, in _validate_args
  File "/tmp/giso_build_30rh2v76/iso/tools/image.py/image.py", line 1560, in _is_iso
  File "/tmp/giso_build_30rh2v76/iso/tools/image.py/image.py", line 987, in _run_text
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'isosize'


Full error:
None

user@server:~$ sudo ./gisobuild/src/gisobuild.py --iso /home/pi/7.7.21/ncs540l-x64-7.7.21.iso --repo /home/pi/7.7.21/ --clean

Building GISO...
Gisobuild script failed, see /home/pi/output_gisobuild/logs/gisobuild.log for more info: Unable to group the following XR packages into blocks:
  xr-bgp-n540-28z4c-7.7.21v1.0.0-1.x86_64
  xr-ipsla-n540-28z4c-7.7.21v1.0.0-1.x86_64
  xr-is-is-n540-28z4c-7.7.21v1.0.0-1.x86_64
  xr-lictrl-n540-28z4c-7.7.21v1.0.0-1.x86_64
  xr-lldp-n540-28z4c-7.7.21v1.0.0-1.x86_64
  xr-mcast-n540-28z4c-7.7.21v1.0.0-1.x86_64
  xr-mpls-oam-n540-28z4c-7.7.21v1.0.0-1.x86_64
  xr-ncs540l-mcast-n540-28z4c-7.7.21v1.0.0-1.x86_64
  xr-ncs540l-netflow-n540-28z4c-7.7.21v1.0.0-1.x86_64
  xr-netflow-n540-28z4c-7.7.21v1.0.0-1.x86_64
  xr-perfmgmt-n540-28z4c-7.7.21v1.0.0-1.x86_64
  xr-telnet-n540-28z4c-7.7.21v1.0.0-1.x86_64
  xr-track-n540-28z4c-7.7.21v1.0.0-1.x86_64
user@server~$`

**Comment by NeilKetley** [comment]
That set of RPMs cannot be complete.  A lot of the ncs540-28z4c RPMs you have are on their own, they have no corresponding top level RPM (e.g. xr-cfgmgr-7.7.21v1.0.3-1.x86_64.rpm is the top level RPM for xr-cfgmgr-n540-28z4c--7.7.21v1.0.3-1.x86_64.rpm) and there are no RPMs that contain the actual software included in that list.  Presumably this set of RPMs was curated from some other source but in doing so a lot of the necessary RPMs have been removed.

Some of the RPMs appear to come from bugfixes (SMUs) because they have versions greater than 1.0.0, while others are at version 1.0.0 which I presume are optional RPMs you want to add to your GISO.  In both cases they are missing top level RPMs, or what we call the partition RPMs, or both.  When you want to create a GISO you should add all the RPMs for the optional packages and bugfixes in the `--repo` directory (the bugfixes can be left within their tarballs, no need to unpack) and the tool will select the RPMs it needs.

On the question about `isosize`, this error is unrelated.  The tool uses the `isosize` utility to check that the ISO it has been presented with is valid.  The error suggests that the utility is not present on your machine.

**Comment by tactic123** [comment]
Thanks for the hint.
I redownloaded all rpms and the bugfixes and now it was successful.
Thanks for the support!

**Comment by tactic123** [comment]
Thanks for the hint.
I actually downloaded everything again and now it worked. Seems some parts were missed by my last attempts.

many thanks for your support
